---
Description: Setup new S3 bucket with a new user who has read only access
Resources: 
  SetupS3Bucket: 
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: "s3-ro-for-sebcarss"
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SetupGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: "ReadOnlyAccessGroup"
  SetupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "s3:ListBucketByTags"
              - "s3:GetLifecycleConfiguration"
              - "s3:GetBucketTagging"
              - "s3:GetInventoryConfiguration"
              - "s3:GetObjectVersionTagging"
              - "s3:ListBucketVersions"
              - "s3:GetBucketLogging"
              - "s3:ListBucket"
              - "s3:GetAccelerateConfiguration"
              - "s3:GetBucketPolicy"
              - "s3:GetObjectVersionTorrent"
              - "s3:GetObjectAcl"
              - "s3:GetEncryptionConfiguration"
              - "s3:GetBucketRequestPayment"
              - "s3:GetObjectVersionAcl"
              - "s3:GetObjectTagging"
              - "s3:GetMetricsConfiguration"
              - "s3:GetBucketPublicAccessBlock"
              - "s3:GetBucketPolicyStatus"
              - "s3:ListBucketMultipartUploads"
              - "s3:GetBucketWebsite"
              - "s3:GetBucketVersioning"
              - "s3:GetBucketAcl"
              - "s3:GetBucketNotification"
              - "s3:GetReplicationConfiguration"
              - "s3:ListMultipartUploadParts"
              - "s3:GetObject"
              - "s3:GetObjectTorrent"
              - "s3:GetBucketCORS"
              - "s3:GetAnalyticsConfiguration"
              - "s3:GetObjectVersionForReplication"
              - "s3:GetBucketLocation"
              - "s3:GetObjectVersion"
            Resource: 
              - "arn:aws:s3:::s3-ro-for-sebcarss/*"
              - "arn:aws:s3:::s3-ro-for-sebcarss"
          -
            Effect: "Allow"
            Action: 
              - "s3:GetAccountPublicAccessBlock"
              - "s3:ListAllMyBuckets"
              - "s3:HeadBucket"
            Resource: "*"
      PolicyName: "ReadOnlyS3Access"
      Groups: 
        - !Ref SetupGroup
  SetupUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: <insert-password>
        PasswordResetRequired: true
      UserName: SebCarssCFStack
      Groups:
       - !Ref SetupGroup
      